# Generated by Django 4.2.1 on 2023-07-28 18:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('info', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='enrollment',
            name='email',
            field=models.EmailField(blank=True, max_length=225, null=True, unique=True),
        ),
        migrations.AlterField(
            model_name='enrollment',
            name='phone',
            field=models.CharField(blank=True, max_length=16, null=True, unique=True),
        ),
    ]
