# Generated by Django 4.2.1 on 2023-07-31 05:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('info', '0002_alter_enrollment_email_alter_enrollment_phone'),
    ]

    operations = [
        migrations.AddField(
            model_name='enrollment',
            name='datetime',
            field=models.DateTimeField(auto_now=True, null=True),
        ),
    ]
